### PR TITLE
Add Zoom video and mic status indicators

### PR DESCRIPTION
**Pull request by torgeir**
Given today's situation I spend a lot of time on zoom, and often times find myself wondering if the video and/or mic is enabled, especially if the app is minimized or on another screen.

This adds optionally visible status indicators for Zoom, when the app is open. The indicators will turn red if the camera or mic respectively is enabled

Dark with video and mic off

Dark with video and mic on

Light with video and mic off

Light with video and mic on

### CODE REVIEW

**Comment by Jean-Tinland** [comment]
That's nice! I'm merging it today! :)

**Comment by Jean-Tinland** [comment]
I've made some minor changes while merging it but it's a good addition, thank you for your work!

**Comment by torgeir** [comment]
Nice, thanks!

What would really would be useful for this kind of “live” widget addition was if the refresh frequency could be bumped for this widget only, but i’m guessing that’s not possible without restructuring things a bit so that the main bar would refresh more often, and a timer of some sort would control the individual widget’s refresh rate. Thoughts?

**Comment by Jean-Tinland** [comment]
Indeed, I had some thoughts about splitting all widgets in data.jsx into several widgets. I had 2 primary concerns about how to implement layout as simple as it is now and the widgets multiplication in Übersicht widget list.

It would of course be a great optimisation.

I'm still thinking about it but it would be a "massive" change in simple-bar.

**Pull request merged**
