### PR TITLE
More Icons

### PR DESCRIPTION
**Pull request by MikoMagni**
Icon for Panic new editor Nova 

image

image

### CODE REVIEW

**Comment by MikoMagni** [comment]
MAMP and MAMP PRO icon.

image

image

**Comment by MikoMagni** [comment]
Telegram Icon 

image

image

**Comment by MikoMagni** [comment]
VLC Icon 

image

image

**Comment by MikoMagni** [comment]
Twitter Icon for Twitter and Tweetbot

image

image

**Comment by MikoMagni** [comment]
zoom.us Icon 

image

image

**Comment by MikoMagni** [comment]
VMware Fusion Icon

image

image

**Comment by Jean-Tinland** [comment]
Nice additions! Thank you!

**Pull request merged**
