### PR TITLE
Add option for switching spaces without yabai when SIP is enabled

### PR DESCRIPTION
**Pull request by jming422**
Hi there, first off just want to say I'm a big fan of simple-bar 😄 

## Summary

 - Add new Util `noYabaiSwitchSpace` that uses Applescript to switch spaces without yabai
   - It sends the default macOS keybinds for space switching (^⭠ and ^⭢) to System Events
 - Add new option `switchSpacesWithoutYabai` to the Settings menu under the Spaces tab to enable this feature
   - Defaults to false, since it's not guaranteed that those keybinds work on every system
 - When trying to switch spaces:
   - If SIP is disabled, use yabai like normal and ignore the `switchSpacesWithoutYabai` setting
   - If SIP is enabled and `switchSpacesWithoutYabai` has been set to `true`, use `noYabaiSwitchSpace` instead of `Yabai.goToSpace`

## Description

I've got yabai and simple-bar all set up on macOS Big Sur 11.5.2 without disabling System Integrity Protection (SIP), and it's working great for my needs. I simply decided the increased security risk wasn't worth yabai's optional features that are available with SIP disabled.

The one thing I really wanted though was the feature in this PR: the ability to switch spaces by clicking on simple-bar's space buttons, even though I still have SIP enabled. Yabai can't do it; it returns a nonzero exit code when asking to switch spaces, since I never installed the scripting addition. However, switching spaces is simple enough that Applescript can do it just fine.

The one caveat is that this assumes the macOS default keybinding for switching spaces left and right: Control + left/right arrows. This caveat is why I chose to make the setting that allows my new behavior `false` by default.

**Edit:** I've been using this branch on my Macbook for the last couple days and it's been working great for me, both with and without external monitors. Even when clicking on the space switcher for a monitor that didn't previously have focus, it's working as expected for me.

I didn't see any contribution guidelines anywhere, so please let me know if there's anything I can change to make my submission better or if you have any feedback.

Thanks!

### CODE REVIEW

**Comment by Jean-Tinland** [comment]
I'll look into this soon!

Thank you for your work :)

**Comment by Jean-Tinland** [comment]
Merged :)

**Comment by tru2dagame** [comment]
Hi @jming422,

Thanks for the switchSpacesWithoutYabai option. I'd like to keep SIP enable as well.

However it seems I can only go right spaces and never goes left...
Could you please advice if I am missing anything?

**Comment by jming422** [comment]
> However it seems I can only go right spaces and never goes left... Could you please advice if I am missing anything?

Hah, looks like you're right -- I admit I haven't used this feature that much recently so I hadn't noticed, but that's definitely a bug. It used to behave as expected, so something must have changed at some point. I probably won't have time to take a look for a while, but if you would like to contribute a fix I'm sure it'd be welcome :)

**Comment by Jean-Tinland** [comment]
Hi, thank you for reporting this ! It should be fixed now :)

**Comment by tru2dagame** [comment]
Thanks a lot.

**Comment by tru2dagame** [comment]
Sorry for such late reply.
Last time I checked, it seems that this e6a17ceadf1f4531a5704297b7c533e4a8a0df96 commit causes this issue. I tried [reverting it](https://github.com/tru2dagame/simple-bar/commit/74bf1bc6beeed4e28b6e5fcb01bab4d794449615) and it works.

I'd like to use it for a while and do a PR fix for it if there are no other problems.
But I've been a little busy at work recently, haven't had time to work on it.

**Pull request merged**
