### PR TITLE
Right click action

### PR DESCRIPTION
**Pull request by rosenpin**
#191 

Here is an example implementation to solve #191 

- [x] Add support for middle click
- [x] Add some default right click actions 
    - [x] Wifi menu on right click
    - [x] Spotify next track 
    - [x] Remap space hover action to right click
- [x] Add support for user widgets

### CODE REVIEW

**Comment by rosenpin** [comment]
There was a mix up with the commits because we worked in parallel. You can just squash them when merging

**Comment by rosenpin** [comment]
I thought about your middle click note.  
I think we should allow middle click options for user widgets for sure, and also consider supporting optional middle click options for default widgets, but not set them by default, since most users won't have access to them

**Comment by Jean-Tinland** [comment]
I merged everything in master! The middle click action can also be triggered with `cmd+click`. Let me know if I missed anything.

**Comment by rosenpin** [comment]
> I merged everything in master! The middle click action can also be triggered with `cmd+click`. Let me know if I missed anything.

Wow that's a great idea! really like it

**Comment by rosenpin** [comment]
Just one small thing, I don't mind it, but it's customary to merge PRs or work from them, so that people who work on them will be credited appropriately.  

Again, I'm cool with it and you added a lot in this case, but it would be nice if next time you could either start the work from the PR as a base, so other contributors will get the appropriate credit (it appears both on the user profile and in the repo history)  
I know from my experience managing open source projects, some people care about it more than others, but it's a good habit to have :)

**Comment by Jean-Tinland** [comment]
Indeed! This time I squashed all the commits so Github isn't automatically recognising this pull request. I usually do not proceed that way (you can see there is a lot of contributors), I'm sorry I was a little too fast.

Anyway I'm always making sure to give credits at the end of the readme each time I merge a pull request (by squashing or not).

I'll do better next time! :)

**Comment by Jean-Tinland** [comment]
And of course thank you for your work, I'm glad other people always bring some fresh ideas :)

**Pull request closed without merging**
