### PR TITLE
Add Spotify element

### PR DESCRIPTION
**Pull request by jamieweavis**
Added Spotify element:
- Displays current track and artist names
- Icon changes based on currently playing/paused
- Clicking the element pauses and unpauses the current track
- Hides when Spotify is closed

Playing:
Screenshot 2020-09-12 at 21 40 36

Paused:
Screenshot 2020-09-12 at 21 40 42

Spotify closed:
Screenshot 2020-09-12 at 21 57 57

Not sure whether this element should be enabled by default?

### CODE REVIEW

**Comment by Jean-Tinland** [comment]
I really like that, I'll merge it as it is. I think it is not a problem to enable it by default for now.
Maybe when I have created some installation scripts, I could let the user choose what "widget" he want to display.

I'd just like to do something to handle long song names because on a 13" screen I'm worried that it would overlap on current process name.

Anyway, thank you for this functionality!

**Comment by jamieweavis** [comment]
That's a good idea, much better than truncating 👍

**Comment by Jean-Tinland** [comment]
I was thinking about something like this:

demo
(The gif is a bit laggy)

If it's okay for you I'll push that :)

**Comment by jamieweavis** [comment]
Looks great! 🚀

**Pull request merged**
