### PR TITLE
Added m1 support

### PR DESCRIPTION
**Pull request by Gitmaster511**
had a problem with m1 macs not being supported. First time making pull request tell me if I did anything wrong.

### CODE REVIEW

**Comment by Gitmaster511** [comment]
I'm not sure if this supports intel macs along with m1.Is there a way to see if the user is intel or m1?

**Comment by Jean-Tinland** [comment]
Hi! I can't merge this as is because It would not work on Intel mac.

Also you don't need to make this change in order to change the yabai path : you can open the bar settings and override the default yabai path directly in the interface.

**Comment by Gitmaster511** [comment]
I see, thank you for that! Also, I created a fork here(https://github.com/Gitmaster511/simple-bar-m1) which is a fork of this with the m1 support. Is it possible to add the link in your Readme so that people with m1's can download the right version?

**Comment by aurelien-brabant** [comment]
No need for a PR to fix this, simply create a symlink:

```sh
ln -sf /opt/homebrew/bin/yabai /usr/local/bin/yabai
```
Works like a charm on my M1.

**Pull request closed without merging**
