### PR TITLE
Fix keyboard layout widget

### PR DESCRIPTION
**Pull request by kvaps**
Currently keyboard indicator is refreshing every 20 seconds, it is unacceptable, because I can switch keyboard layouts much frequent.

PR also includes enhancement to use single awk script to parse layout instead of egrep + sed + sed

### CODE REVIEW

**Comment by Jean-Tinland** [comment]
I merged this but I remove you refresh frequency update as you can now directly update it in simple-bar's settings. :)

Thank you for your contribution!

**Comment by kvaps** [comment]
Hi, I just updated space-bar version from master, and I still don't see any "Keyboard" tab in my settings.

**Comment by Jean-Tinland** [comment]
Indeed, there was some mistakes in this update, this should be fixed now. :)

**Comment by kvaps** [comment]
Yeah, much better now. Thanks a lot! ❤️

**Pull request merged**
