### PR TITLE
add VPN widget

### PR DESCRIPTION
**Pull request by d-miketa**
Cleaned up PR for adding Viscosity support to simple-bar.

### CODE REVIEW

**Comment by Jean-Tinland** [comment]
Thanks, I'll merge this soon :)

**Comment by Jean-Tinland** [comment]
I merged it in master. I simple added a field in settings in which you can set your Viscosity connection name. This VPN widget is disabled by default.

Let me know if I broke anything during the merge.

Thanks again!

**Comment by d-miketa** [comment]
Great, thank you! First PR achieved haha.

One small thing, which you may be able to trivially fix: the connection isn't picked up on when the VPN name includes a space. E.g. mine is "office VPN", but typing that into simple-bar doesn't work; on the other hand typing in "office" _does_ work, even though Viscosity knows the connection under a longer name.

**Comment by Jean-Tinland** [comment]
I'll look into it more soon, It is weird I can't tell why it is not working for now.

**Comment by Jean-Tinland** [comment]
This should normally by fixed in my latest commit, It was due to an escaping quotes/dbquotes problem.

Thanks, that was a nice pull request! :)

**Pull request merged**
